version: "3.2"
services:
  mongo:
    build:
      context: ./mongo
    ports:
     - "27017:27017/tcp"  
    env_file:
     - .env     
    volumes:      
      - ./mongo/storage:/data/db
    network_mode: "host"    

  app:
    build:
      context: ./app
    env_file:
      - .env     
    volumes:      
      - ./app/app:/app
    ports:
      - "8000:8000/tcp"                        
    network_mode: "host"       

  mongo-express:
    build:
      context: ./mongo-express
    ports:
     - "8081:8081/tcp"  
    env_file:
     - .env            
    restart: always
    network_mode: "host"    



